trigger:
- development
- main

resources:
  repositories:
  - repository: templates
    type: git
    name: DevOps/azure-devops-templates
    ref: refs/tags/v1.0.0

variables:
- template: common/variables.yml@templates
- template: common/branch-env.yml@templates

stages:
- template: pipelines/dual-angular-webapps.yml@templates
  parameters:
    azureSubscription: 'rescuedigital (a1a51b50-b8e7-410c-946b-b239872d9b79)'

    apps:
    - name: weber
      appService: wr-hub-eu
      resourceGroup: wr-hub-eu-rg
      buildDevCmd: build-weber-dev
      buildProdCmd: build-weber-live

    - name: genesis
      appService: genesis-hub-us
      resourceGroup: grs-hub-us-rg
      buildDevCmd: build-genesis-dev
      buildProdCmd: build-genesis-live
